/** Стили витрины (заглушки — можно править под бренд). @param {number} styleId */
export function shopThemeClass(styleId) {
  const id = Number(styleId) || 1;
  const map = {
    1: {
      shell: 'bg-[#f7f8fb] text-slate-900',
      card: 'bg-white border-slate-200',
      accent: 'text-sky-700',
      btn: 'bg-sky-600 text-white',
      muted: 'text-slate-500',
      font: 'font-sans',
      panel: 'bg-white border-slate-200',
      panelText: 'text-slate-900',
      panelSubtle: 'text-slate-600',
      panelBorder: 'border-slate-200',
    },
    2: {
      shell: 'bg-[#fff8ef] text-[#3f2f1f]',
      card: 'bg-white border-amber-200',
      accent: 'text-amber-700',
      btn: 'bg-amber-600 text-white',
      muted: 'text-amber-800/70',
      font: 'font-serif',
      panel: 'bg-[#fffdf8] border-amber-200',
      panelText: 'text-[#3f2f1f]',
      panelSubtle: 'text-amber-900/75',
      panelBorder: 'border-amber-200',
    },
    3: {
      shell: 'bg-[#0a0a10] text-white',
      card: 'bg-white/[0.06] border-white/10',
      accent: 'text-fuchsia-300',
      btn: 'bg-fuchsia-500 text-white',
      muted: 'text-white/60',
      font: 'font-sans',
      panel: 'bg-[#161623] border-white/10',
      panelText: 'text-white',
      panelSubtle: 'text-white/70',
      panelBorder: 'border-white/10',
    },
    4: {
      shell: 'bg-[#0f1719] text-teal-50',
      card: 'bg-teal-900/20 border-teal-600/25',
      accent: 'text-teal-300',
      btn: 'bg-teal-500 text-teal-950',
      muted: 'text-teal-100/55',
      font: 'font-mono',
      panel: 'bg-[#13262a] border-teal-500/25',
      panelText: 'text-teal-50',
      panelSubtle: 'text-teal-100/70',
      panelBorder: 'border-teal-500/25',
    },
    5: {
      shell: 'bg-[#111827] text-slate-100',
      card: 'bg-slate-800/40 border-slate-600/30',
      accent: 'text-indigo-300',
      btn: 'bg-indigo-500 text-white',
      muted: 'text-slate-300/70',
      font: 'font-sans',
      panel: 'bg-[#1a2338] border-slate-500/25',
      panelText: 'text-slate-100',
      panelSubtle: 'text-slate-300/75',
      panelBorder: 'border-slate-500/25',
    },
    6: {
      shell: 'bg-[#f4f6ff] text-[#1f2450]',
      card: 'bg-white border-indigo-200 shadow-sm',
      accent: 'text-indigo-700',
      btn: 'bg-indigo-600 text-white',
      muted: 'text-indigo-500',
      font: 'font-serif',
      panel: 'bg-white border-indigo-200',
      panelText: 'text-[#1f2450]',
      panelSubtle: 'text-indigo-700/75',
      panelBorder: 'border-indigo-200',
    },
  };
  return map[id] || map[1];
}

export const SHOP_STYLE_LABELS = [
  { id: 1, name: 'Светлый Sky', swatches: ['#f7f8fb', '#0ea5e9', '#ffffff'], font: 'Sans' },
  { id: 2, name: 'Тёплый Sand', swatches: ['#fff8ef', '#d97706', '#ffffff'], font: 'Serif' },
  { id: 3, name: 'Neon Dark', swatches: ['#0a0a10', '#d946ef', '#1f1f2c'], font: 'Sans' },
  { id: 4, name: 'Terminal Teal', swatches: ['#0f1719', '#14b8a6', '#123033'], font: 'Mono' },
  { id: 5, name: 'Midnight Indigo', swatches: ['#111827', '#6366f1', '#1f2937'], font: 'Sans' },
  { id: 6, name: 'Lavender Light', swatches: ['#f4f6ff', '#4f46e5', '#ffffff'], font: 'Serif' },
];
